### ISSUE TITLE
QUESTION: Its possible use as nodejs module?

### ISSUE THREAD

**Issue by taufpate** [uhppoted/node-red-contrib-uhppoted#7]
I am looking to be able to use uhppote within an application developed in electronjs, is it possible to use this in some way maybe as an npm module?

**Comment by uhppoted** [comment]
Hi,

The short answer is that _"yes, it's possible but just not very elegant because the module is fairly specifically engineered for the NodeRED architecture"_. 

Basically you have to install the code locally as a development module and then use the low level functions exposed by the `uhppoted.js` module:

1. Clone the [node-red-contrib-uhppoted](https://github.com/uhppoted/node-red-contrib-uhppoted) to your local project directory
   ```
   git clone https://github.com/uhppoted/node-red-contrib-uhppoted.git
   ```
2. Install the module locally to resolve the dependencies:
   ```
   npm install ./node-red-contrib-uhppoted
   ```
3. Import `uhppoted.js` and `opcodes.js` as source modules:
4. Create `context` and `config` objects for the `uhppoted` calls:
5. Use the `uhppoted` _get_, _set_, _broadcast_ and _listen_ calls directly:

I've attached a sample HTTP server that demonstrates the last 2 steps for the `get-device` call so that you can see what it looks like. The `uhppoted` functions return a _Promise_ that resolves to the same _Javascript_ object you would get as the message payload in NodeRED.

HTH :-)

Hmmm .. it probably shouldn't be too difficult to re-engineer the NodeRED module as a standalone NodeJS module - I'll put it on the (ever-growing) TODO list.



[app.js.zip](https://github.com/uhppoted/node-red-contrib-uhppoted/files/6448583/app.js.zip)

**Comment by taufpate** [comment]
Great, thank you so much! 

I will try in the next few days, thanks again

**Comment by uhppoted** [comment]
Hi,

Am going to leave this open for a bit - after some experimentation it turns out that migrating the NodeRED code to NodeJS is relatively straightforward so I've created a new repository for a NodeJS implementation of the UHPPOTE API:

[uhppoted-nodejs](https://github.com/uhppoted/uhppoted-nodejs)

It's still in the very early stages of development so expect the API to be a bit unstable while the structure and architecture shake out into something cleaner, but it will probably be a whole lot simpler to use compared to extracting the useful bits out of the NodeRED project.

**Comment by uhppoted** [comment]
Done (finally :-)) - and published to NPM:

- https://www.npmjs.com/package/uhppoted

**Comment by taufpate** [comment]
Great! nice work! I will test the release next week, tks again!
