### ISSUE TITLE
Contact state

### ISSUE THREAD

**Issue by dastrix80** [uhppoted/node-red-contrib-uhppoted#8]
Hi there

Ive got all functions working with node red except being able to pull the status of the door contact sensor, the WebUI for the board shows it correctly, but I can't seem to pull the state into a node inside NR.

Any help would be great!

Thanks!

**Comment by uhppoted** [comment]
Hi,

Is your door contact sensor wired to one of the S1 to S4 inputs? Then the door status should be available in the _doors_ field of the `get-status` node - if you have _debug_ set in the configuration you should be able to see bytes 28 to 31 reflecting the status of the S1 to S4 inputs.

The S1 to S4 inputs expect a relay contact configured so that if it is closed the door is indicated as `true`/_closed_ ('fail safe').

**Comment by dastrix80** [comment]
Great, thanks I can see that now !!! Just need to work out how to input that true/closed into an OpenHAB item

**Comment by uhppoted** [comment]
Sounds like you're (more or less) good to go? Am going to close this - feel free to reopen if you need  to.
